# Generated by Django 5.0.6 on 2024-06-26 19:41

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_file_image_text_video_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='owner',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='body',
        ),
        migrations.AddField(
            model_name='course',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.category'),
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
