# Generated by Django 5.0.6 on 2024-06-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_managers_rename_owner_course_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
