# Generated by Django 5.0.6 on 2024-07-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_file_title_remove_image_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students_ids',
            new_name='students',
        ),
    ]
