# Generated by Django 5.0.6 on 2024-07-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursecomment_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
