# Generated by Django 5.0.6 on 2024-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='author',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='author',
            field=models.PositiveIntegerField(),
        ),
    ]
