# Generated by Django 5.0.6 on 2024-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_author_alter_coursecomment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='users_seen',
            field=models.JSONField(default=list),
        ),
    ]
