# Generated by Django 5.0.7 on 2024-08-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_slug_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='users_seen',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
