# Generated by Django 5.0.7 on 2024-08-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncomment',
            name='is_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='quote_text',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessoncomment'),
        ),
    ]
