# Generated by Django 5.0.6 on 2024-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories_liked',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
