# Generated by Django 5.0.6 on 2024-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_categories_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories_liked',
            field=models.JSONField(default=list),
        ),
    ]
